travis:
  secure:
    BINSTAR_TOKEN: eIcFXjq3g6WLn7/J2f+7VBooWo8At1EC1NIiLMDBiP+pS7iRSIa10kTVbU5+P964JFH31o1YVxJ/06KDcBXtm3PR/VCUeYTCye3bOxFCyssiku6xEa/27jwAc/aZXp+Vtk6gHf4eyz7JB7V2ryH65qTaX4EY/rXHS/deWj6R0ZpvskxYDG+X2RRzdcK7OpLlmcIjaoEOGhEu7IZdYPQ219Xue1mgtK4382jEh5WjQld1MSOXXrcAdAImNLnrrX+KmXN3l57Og+xcz6J6giJeY70wMZItENFxTIWfZFYiVUemwItwZheIaoUWxSPQqNfUvxKBULcgJmtAGHofXMEUY8SiFqDpo4d0YFBxf4hajLf8Jb05Bnqkk0stVeOAZgVLWnJ30NAaZGw9bc5h0wzytD+vjojHr4gtmEvkd2870V0VcZbjVDUkFOUbF+LRiNWM8PkyJz4pTkN5zac93yWX3ckFXnTM6pyYGcY0SGSPsXsjIACRBU5+L6iRVlfHZpl7w4gVN9ChhOvR3NvP8L0WGl9W1HmQUy6IafqjpVS8p5HJxBSPNNMoOt/CZdJH8q2DIDMwgYXM1S6TerPFhy28Aml4UTFtx7yjIT5XGUs8MTSpKS31RXbeyOvztrrI+FJdNJtjkfuqMYoG5dhpMF7LAh5duM79F22lbwRocPAWMJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
